version: '3.8'

services:
  web:
    build: 
      context: .
      args:
        - ALLOWED_HOSTS=${ALLOWED_HOSTS}
        - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - static_volume:/app/staticfiles
      - ./frontend/build:/app/frontend/build
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --timeout 300  # Increase timeout

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

volumes:
  static_volume: